ip_forward: true
network_compression_threshold: 256
stats: 0cc7ebee-cb22-49f3-bed5-72b4bc4ae4f6
groups:
  Darunia18:
  - admin
  - mod
  - helper
servers:
  survival:
    motd: '&1NightfallMC Survival'
    address: localhost:25565
    restricted: false
  creative:
    motd: '&1NightfallMC Creative'
    address: localhost:25565
    restricted: false
timeout: 30000
player_limit: -1
listeners:
- query_port: 25577
  motd: '&1NightfallMC'
  priorities:
  - survival
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: false
  host: 0.0.0.0:25577
  forced_hosts:
    s.nightfallmc.net: survival
    c.nightfallmc.net: creative
  max_players: 1
  tab_size: 60
  ping_passthrough: false
  force_default_server: false
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  - gssentials.announce.join
  - gssentials.announce.quit
  - gssentials.chat
  - gssentials.find
  - gssentials.friend
  - gssentials.ignore
  - gssentials.join
  - gssentials.list
  - gssentials.message
  - gssentials.message.global
  cplus: null
  vip: null
  vipplus:
  - gssentials.message.color
  mvp: null
  vet: null
  helper:
  - bat.comment
  - bat.kick
  - bat.mute
  - gssentials.admin.alert
  - gssentials.admin.notify
  mod:
  - bat.ban
  - gssentials.admin.chat
  - gssentials.admin.hide
  - gssentials.admin.hide.bypass
  - gssentials.admin.lookup
  - gssentials.admin.lookup.info
  - gssentials.admin.spy
  - gssentials.message.click
  - gssentials.message.hover
  - gssentials.slap
  admin:
  - bat.admin
  - bungeetablistplus.admin
  - bungeetablistplus.command
  - gssentials.admin.reload
  - gssentials.admin.send
  - gssentials.admin.sendall
  - gssentials.admin.spy.command
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - gssentials.list.offline
  - gssentials.list.restricted
online_mode: true
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000
