ip_forward: true
network_compression_threshold: 256
stats: 0cc7ebee-cb22-49f3-bed5-72b4bc4ae4f6
permissions:
groups:
servers:
  survival:
    motd: '&1NightfallMC Survival'
    address: localhost:25565
    restricted: false
  creative:
    motd: '&1NightfallMC Creative'
    address: localhost:25565
    restricted: false
timeout: 30000
listeners:
- query_port: 25577
  motd: '&1NightfallMC'
  priorities:
  - survival
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: false
  host: 0.0.0.0:25577
  forced_hosts:
    s.nightfallmc.net: survival
    c.nightfallmc.net: creative
  max_players: 1
  tab_size: 60
  ping_passthrough: false
  force_default_server: false
player_limit: -1
online_mode: true
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000
